from typing import Protocol
from tasks.models import Task, TaskCreate, TaskUpdate
from typing import Optional


class TaskRepository(Protocol):
    def list_tasks(self) -> list[Task]: ...

    def create_task(self, task_create: TaskCreate) -> Optional[Task]: ...

    def get_task(self, task_id: int) -> Optional[Task]: ...

    def update_task(self, task_id: int, task_update: TaskUpdate) -> Optional[Task]: ...

    def delete_task(self, task_id: int) -> Optional[Task]: ...

    def truncate(self) -> None: ...
